name=SoftTimerAdvance
version=1.0.1
author=Hompain
maintainer=Hompain
sentence=Versatile soft timers with extensive functionality.
paragraph=Implements a software timer manager. Features: timers, delayed calls, timeouts, and threads.
category=Timing
url=https://github.com/HOMPAIN/SoftTimerAdvance
architectures=*
